[all]
172.17.0.2
172.17.0.3
172.17.0.4
node1 ansible_user=root ansible_host=localhost ansible_port=2001 ansible_private_key_file=/home/test/.ssh/id_rsa
node2 ansible_user=root ansible_host=localhost ansible_port=2002 ansible_private_key_file=/home/test/.ssh/id_rsa
node3 ansible_user=root ansible_host=localhost ansible_port=2003 ansible_private_key_file=/home/test/.ssh/id_rsa
[linux]
172.17.0.2
172.17.0.3
172.17.0.4
