- name: this playbook installs nginx 
  hosts: all
  tasks:
    - name: testing ping
      ping:
    - name: Startng of  nginx
      service: name=nginx state=restarted
#    - name: install pre-requisite- epel release
#      yum: name=epel-release
#    - name: fix epel repo
#      shell: sed -i "s/mirrorlist=https/mirrorlist=http/" /etc/yum.repos.d/epel.repo
#    - name: install nginx
#      yum: name=nginx
#    - name: Start nginx
#      sysctl: name=nginx -reload
